version: '2'
services:
  ecommerce-rabbit:
    image: rabbitmq:3-management
    container_name: ecommerce-rabbit
    hostname: ecommerce-rabbit
    ports:
      - "5050:15672"
      - "5672:5672"
    volumes:
      - $PWD/docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
  order-service:
    container_name: order-service
    build: order-service
    ports:
      - "8081:8081"
    depends_on:
      - ecommerce-rabbit
  payment-service:
    container_name: payment-service
    build: payment-service
    ports:
      - "8082:8082"
    depends_on:
      - ecommerce-rabbit
      - order-service
